apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/prometheus-clusterRole.yaml
- upstream/prometheusAdapter-clusterRole.yaml
- upstream/prometheus-serviceAccount.yaml
- upstream/alertmanager-podDisruptionBudget.yaml
- upstream/prometheusAdapter-clusterRoleServerResources.yaml
- upstream/blackboxExporter-serviceAccount.yaml
- upstream/prometheusAdapter-service.yaml
- upstream/prometheus-roleBindingSpecificNamespaces.yaml
- upstream/kubeStateMetrics-serviceAccount.yaml
- upstream/prometheus-roleBindingConfig.yaml
- upstream/grafana-service.yaml
- upstream/nodeExporter-service.yaml
- upstream/nodeExporter-networkPolicy.yaml
- upstream/prometheusOperator-prometheusRule.yaml
- upstream/prometheusAdapter-configMap.yaml
- upstream/blackboxExporter-networkPolicy.yaml
- upstream/kubernetesControlPlane-serviceMonitorCoreDNS.yaml
- upstream/prometheusAdapter-clusterRoleAggregatedMetricsReader.yaml
- upstream/prometheusAdapter-serviceAccount.yaml
- upstream/prometheusOperator-serviceMonitor.yaml
- upstream/prometheusAdapter-podDisruptionBudget.yaml
- upstream/blackboxExporter-clusterRole.yaml
- upstream/grafana-deployment.yaml
- upstream/nodeExporter-serviceAccount.yaml
- upstream/blackboxExporter-configuration.yaml
- upstream/blackboxExporter-service.yaml
- upstream/grafana-dashboardDefinitions.yaml
- upstream/prometheusAdapter-roleBindingAuthReader.yaml
- upstream/grafana-dashboardDatasources.yaml
- upstream/prometheusAdapter-apiService.yaml
- upstream/grafana-config.yaml
- upstream/grafana-dashboardSources.yaml
- upstream/prometheus-networkPolicy.yaml
- upstream/kubernetesControlPlane-prometheusRule.yaml
- upstream/grafana-serviceAccount.yaml
- upstream/kubeStateMetrics-clusterRole.yaml
- upstream/kubePrometheus-prometheusRule.yaml
- upstream/prometheusOperator-clusterRoleBinding.yaml
- upstream/kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- upstream/alertmanager-serviceAccount.yaml
- upstream/nodeExporter-clusterRoleBinding.yaml
- upstream/prometheus-prometheus.yaml
- upstream/prometheus-clusterRoleBinding.yaml
- upstream/grafana-networkPolicy.yaml
- upstream/prometheusOperator-service.yaml
- upstream/kubeStateMetrics-serviceMonitor.yaml
- upstream/prometheus-roleConfig.yaml
- upstream/nodeExporter-prometheusRule.yaml
- upstream/prometheusAdapter-clusterRoleBinding.yaml
- upstream/nodeExporter-daemonset.yaml
- upstream/grafana-prometheusRule.yaml
- upstream/blackboxExporter-clusterRoleBinding.yaml
- upstream/alertmanager-networkPolicy.yaml
- upstream/prometheusAdapter-serviceMonitor.yaml
- upstream/prometheusAdapter-networkPolicy.yaml
- upstream/prometheus-serviceMonitor.yaml
- upstream/prometheus-roleSpecificNamespaces.yaml
- upstream/alertmanager-alertmanager.yaml
- upstream/prometheusOperator-clusterRole.yaml
- upstream/blackboxExporter-serviceMonitor.yaml
- upstream/prometheus-podDisruptionBudget.yaml
- upstream/alertmanager-prometheusRule.yaml
- upstream/kubernetesControlPlane-serviceMonitorApiserver.yaml
- upstream/blackboxExporter-deployment.yaml
- upstream/prometheus-service.yaml
- upstream/alertmanager-secret.yaml
- upstream/prometheus-prometheusRule.yaml
- upstream/nodeExporter-clusterRole.yaml
- upstream/kubeStateMetrics-networkPolicy.yaml
- upstream/kubeStateMetrics-deployment.yaml
- upstream/alertmanager-serviceMonitor.yaml
- upstream/kubeStateMetrics-service.yaml
- upstream/prometheusOperator-networkPolicy.yaml
- upstream/kubeStateMetrics-clusterRoleBinding.yaml
- upstream/prometheusOperator-serviceAccount.yaml
- upstream/nodeExporter-serviceMonitor.yaml
- upstream/prometheusAdapter-deployment.yaml
- upstream/kubeStateMetrics-prometheusRule.yaml
- upstream/alertmanager-service.yaml
- upstream/prometheusOperator-deployment.yaml
- upstream/kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml
- upstream/grafana-serviceMonitor.yaml
- upstream/kubernetesControlPlane-serviceMonitorKubelet.yaml
- upstream/prometheusAdapter-clusterRoleBindingDelegator.yaml
- istio_sm.yaml
- controller_sm.yaml
- prometheus_ingress.yaml
#- stats_filter.yaml
patchesStrategicMerge:
- prom_sa.yaml
